export { default as Characters } from "../pages/Characters";
export { default as Planets } from "../pages/Planets";
export { default as Starships } from "../pages/Starships";
export { default as Main } from "../layout/Main";
export { default as Layout } from "../layout/Layout";
export { default as Home } from "../pages/Home";
export { default as CharacterDetail } from "../pages/CharacterDetail";
export { default as PlanetDetail } from "../pages/PlanetDetail";
export { default as StarshipDetail } from "../pages/StarshipDetail";